# Generated by Django 4.1.5 on 2023-03-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=20)),
                ('state', models.UUIDField(null=True)),
                ('code', models.CharField(max_length=100)),
                ('access_token', models.CharField(default='', max_length=100)),
                ('message', models.CharField(default='', max_length=500)),
                ('subscribed', models.BooleanField(default=False)),
            ],
        ),
    ]
